export const ANSWERS = [
  'APPLE','REACT','ROUTE','STATE','ARRAY','LOGIC','WORLD','DEBUG','MOUSE','BOARD'
]

export const DICTIONARY = new Set([
  ...ANSWERS,
  'ALERT','ABOUT','AFTER','OTHER','INPUT','ERROR','CLICK','TOKEN','ENTER','LOCAL',
  'VALUE','PRINT','SCOPE','EVENT','INDEX','TITLE','STYLE','COLOR','GREEN','YIELD',
  'TRACE','QUEUE','APPLE','REACT','ROUTE','STATE','ARRAY','LOGIC','WORLD','DEBUG','MOUSE','BOARD'
])
